# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# node_require('react-native/scripts/react_native_pods.rb')
# node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_modular_headers! #// for Xcode 12 and above to work 

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'sevenValetDrivers' do
  config = use_native_modules!
  flags = get_default_flags()

  # FCM(Firebase push notification) setup scripts start --->
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps' # This script is for the google maps if not needed then please skip this one
  # <--- FCM(Firebase push notification) setup scripts End 


  use_frameworks! :linkage => :static # add
  $RNFirebaseAsStaticFramework = true # add

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

   # Enable Hermes explicitly (if used)
   if ENV['HERMES_ENABLED'] == 'true'
    use_frameworks! :linkage => :static
  end

  # target 'newsamarabizTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # FIXES BUILD ON Apple Silicon M1+
    projects = installer.aggregate_targets
    .map{ |t| t.user_project }
    .uniq{ |p| p.path }

    # projects.each do |project|
    #   project.build_configurations.each do |config|
    #     config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    #   end
    # end
  end
end
